#ifndef __FlipDataViewer__
#define __FlipDataViewer__

/**
@file
Subclass of DataViewer, which is generated by wxFormBuilder.
*/

#include "Flip.h"
#include "FlipMain.h"

//// end generated include

/** Implementing DataViewer */
class FlipDataViewer : public DataViewer
{
public:
	/** Constructor */
	FlipDataViewer(FlipMain *parent);
	//// end generated class members

private:
	void OnSpinUp(wxEvent &event);
	FlipMain *m_mainFrame;
};

#endif // __FlipDataViewer__
