#ifndef __FlipMain__
#define __FlipMain__

/**
@file
Subclass of Main, which is generated by wxFormBuilder.
*/

#include "Flip.h"

//// end generated include

#include "FlipProgramLog.h"
#include <memory>
#include <wx/hashmap.h>

WX_DECLARE_STRING_HASH_MAP(wxString, TemplateMap);

/** Implementing Main */
class FlipMain : public Main
{
	public:
		/** Constructor */
		FlipMain( wxWindow* parent );
	//// end generated class members
		// cutom constructor declared below here
		FlipMain(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style);
		~FlipMain();
	    TemplateMap ReadUserTemplates(const wxArrayString& readPaths);


	// custom class members are below here
	private:
		void OnAbout(wxCommandEvent& event);
		void OnQuit(wxCommandEvent& event);
		void OnShowProgramLog(wxCommandEvent& event);

		std::unique_ptr<FlipProgramLog> m_programLog;
};

#endif // __FlipMain__
