#ifndef __FlipDataViewer__
#define __FlipDataViewer__

/**
@file
Subclass of DataViewer, which is generated by wxFormBuilder.
*/

#include "Flip.h"
#include "FlipMain.h"

//// end generated include

// declare custom events
wxDECLARE_EVENT(EVT_FLIPDATAVIEWER_BTNSAVE_CLICKED, wxCommandEvent);
wxDECLARE_EVENT(EVT_FLIPDATAVIEWER_CONTINUEPROCESSING_CLICKED, wxCommandEvent);
wxDECLARE_EVENT(EVT_FLIPDATAVIEWER_FINISHPROCESSING_CLICKED, wxCommandEvent);

/** Implementing DataViewer */
class FlipDataViewer : public DataViewer
{
public:
	/** Constructor */
	FlipDataViewer(FlipMain *parent);
	//// end generated class members
	bool GetBtnContinueProcessingAbility();
	bool GetBtnFinishProcessingAbility();
	bool GetBtnSaveAbility();
	void ToggleBtnContinueProcessingAbility();
	void ToggleBtnFinishProcessingAbility();
	void ToggleBtnSaveAbility();

private:
	void OnBtnContinueProcessing(wxEvent &event);
	void OnBtnFinishProcessing(wxEvent &event);
	void OnBtnSave(wxEvent &event);
	void OnClose(wxEvent &event);
	void OnFlipMainLaunchClicked(wxEvent &event);
	void OnSpin(wxEvent &event);
	// void OnSpinUp(wxEvent &event);
	FlipMain *m_mainFrame;
	std::unordered_map<wxSpinButton *, wxTextCtrl *> m_uomap_SpinToTextCtrl;
};

#endif // __FlipDataViewer__
