#ifndef __FlipProgramLog__
#define __FlipProgramLog__

/**
@file
Subclass of ProgramLog, which is generated by wxFormBuilder.
*/

#include "Flip.h"

//// end generated include

/** Implementing ProgramLog */
class FlipProgramLog : public ProgramLog
{
	public:
		/** Constructor */
		FlipProgramLog( wxWindow* parent );
	//// end generated class members

	// custom added members and methods
	void LogMessage(const wxString& message);
	void OnClose(wxCloseEvent& event);





};

#endif // __FlipProgramLog__
