#ifndef __FlipTemplateEditor__
#define __FlipTemplateEditor__

/**
@file
Subclass of TemplateEditor, which is generated by wxFormBuilder.
*/

#include "FlipMain.h"
#include <wx/timer.h>

//// end generated include

/** Implementing TemplateEditor */
class FlipTemplateEditor : public TemplateEditor
{
public:
	/** Constructor */
	FlipTemplateEditor(FlipMain *parent);
	//// end generated class members
	void OnBtnAddTemplate(wxCommandEvent &event);
	void OnBtnRemoveTemplate(wxCommandEvent &event);
	void OnClose(wxCloseEvent &event);
	void OnTemplateChoiceChanged(wxCommandEvent &event);
	void OnTemplateEditorAutoSaveTimeout(wxTimerEvent &event);
	void OnTemplateEditorTextChanged(wxCommandEvent &event);
	void OnTemplateListUpdated(wxCommandEvent &event);

	wxChoice *m_wxChoicePtr_Templates; // ptr to mainFrame's wxChoice for available and currently selected templates
private:
	bool
		m_templateFileWasDeleted = false,
		m_templateFileWasLoaded = false;
	FlipMain *m_mainFrame;
	int m_teAutoSaveDelay = 2500;
	wxString m_teCurrentTemplate;
	wxTimer m_teAutoSaveTimer;
};

#endif // __FlipTemplateEditor__
