#ifndef __FlipTemplateEditor__
#define __FlipTemplateEditor__

/**
@file
Subclass of TemplateEditor, which is generated by wxFormBuilder.
*/

#include "FlipMain.h"
#include <wx/timer.h>

//// end generated include

/** Implementing TemplateEditor */
class FlipTemplateEditor : public TemplateEditor
{
public:
	/** Constructor */
	FlipTemplateEditor(FlipMain *parent);
	//// end generated class members
	void OnBtnAddTemplate(wxCommandEvent &event);
	void OnClose(wxCloseEvent &event);
	void OnTemplateChoiceChanged(wxCommandEvent &event);
	void OnTemplateEditorAutoSaveTimeout(wxTimerEvent &event);
	void OnTemplateEditorTextChanged(wxCommandEvent &event);
	void OnTemplateListUpdated(wxCommandEvent &event);

	wxChoice *m_wxChoice_Templates; // ptr to parent's wxChoice for templates
private:
	FlipMain *m_mainFrame;
	wxString m_teCurrentTemplate;
	wxTimer m_teAutoSaveTimer;
	int m_teAutoSaveDelay = 5000;
};

#endif // __FlipTemplateEditor__
