#ifndef __FlipTemplateEditor__
#define __FlipTemplateEditor__

/**
@file
Subclass of TemplateEditor, which is generated by wxFormBuilder.
*/

#include "Flip.h"

//// end generated include

WX_DECLARE_STRING_HASH_MAP(wxString, TemplateMap);

/** Implementing TemplateEditor */
class FlipTemplateEditor : public TemplateEditor
{
public:
	/** Constructor */
	FlipTemplateEditor(wxWindow *parent);
	//// end generated class members
	void OnClose(wxCloseEvent &event);

	wxChoice *m_ptr_UseTemplates;
};

#endif // __FlipTemplateEditor__
